/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_template;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author R.BLack
 */
public class viewAndEditStock extends javax.swing.JFrame {

    /**
     * Creates new form viewAndEditStock
     */
    public viewAndEditStock() {
        initComponents();
        loadList();
        //center window
        setLocationRelativeTo(null);
    }
    
    /**Reads through the stock.txt file and adds each line to a list model
     * lstCustomers is then set to the list model so that it will have the customer info
     * @author R.BLack
     */
    public void loadList(){
        //line variable used to read each line in list
        String line;
        
        //create new list model
        DefaultListModel listModel = new javax.swing.DefaultListModel();
        
        try {
            //create new reader
            FileReader fr = new FileReader("storage\\stock.txt");
            
            //create buffer reader to extend reader
            BufferedReader br = new BufferedReader(fr);
            
            //read until empty line
            while ((line = br.readLine()) != null) {
                //add line to list model
                listModel.addElement(line);
            }
            
            //close file
            br.close();
            fr.close();
            
        } catch (FileNotFoundException fnfEx) {
            //show error window
            JOptionPane.showMessageDialog(null,"There was an error reading the file.\n" + fnfEx,"Error",0);
            
        } catch (IOException ex) {
            //show error window
            JOptionPane.showMessageDialog(null,"There was an error reading the file.\n" + ex,"Error",0);
            
        }
        
        //set the lstCustomers list to the list model with all customer info
        lstStock.setModel(listModel);
    }
    
    /**This method returns true or false if string is numeric
     * @param str this is the string that will be checked
     * @author R.BLack
     */
    public static boolean isNumeric(String str) {
        return str != null && str.matches("[-+]?\\d*\\.?\\d+");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstStock = new javax.swing.JList<>();
        txtIDNum = new javax.swing.JFormattedTextField();
        txtQuantity1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 240, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 167, 250), 2), "View and Edit Stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(48, 41, 66))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblID.setForeground(new java.awt.Color(48, 41, 66));
        lblID.setText("ID Number");

        txtName.setBackground(new java.awt.Color(210, 201, 240));
        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(48, 41, 66));
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 167, 250), 2));

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(48, 41, 66));
        lblName.setText("Name");

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(48, 41, 66));
        lblQuantity.setText("Quantity");

        btnMenu.setBackground(new java.awt.Color(210, 201, 240));
        btnMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(48, 41, 66));
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(210, 201, 240));
        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(48, 41, 66));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(210, 201, 240));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(48, 41, 66));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lstStock.setBackground(new java.awt.Color(241, 240, 255));
        lstStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 167, 250), 2));
        lstStock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lstStock.setForeground(new java.awt.Color(48, 41, 66));
        lstStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstStock);

        txtIDNum.setBackground(new java.awt.Color(210, 201, 240));
        txtIDNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 167, 250), 2));
        txtIDNum.setForeground(new java.awt.Color(48, 41, 66));
        txtIDNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtIDNum.setToolTipText("");
        txtIDNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIDNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDNumActionPerformed(evt);
            }
        });

        txtQuantity1.setBackground(new java.awt.Color(210, 201, 240));
        txtQuantity1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 167, 250), 2));
        txtQuantity1.setForeground(new java.awt.Color(48, 41, 66));
        txtQuantity1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtQuantity1.setToolTipText("");
        txtQuantity1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtQuantity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantity1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblID)
                            .addComponent(lblName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIDNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(lblQuantity)
                                .addGap(18, 18, 18)
                                .addComponent(txtQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblID)
                    .addComponent(txtIDNum, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName)
                    .addComponent(txtQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        //create new menu
        Menu menuPage = new Menu();
        //show menu
        menuPage.show();
        //dispose current window
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        //unselect any records so that it doesn't refill text boxes
        lstStock.clearSelection();

        // set all textboxes to ""
        txtName.setText("");
        txtQuantity1.setText("");
        txtIDNum.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //String each line
        String line;

        //array of each record from the list
        //.getModel().getSize() will count the amount of record currently in the list
        String[] records = new String[lstStock.getModel().getSize()];

        // get values from textbox
        String idNum = txtIDNum.getText().strip();
        String name = txtName.getText().strip();
        String quantity = txtQuantity1.getText().strip();

        //check if they are valid
        //create an error boolean that will be used to check if
        //an entry should be written into the text file or not
        boolean error = false;

        //check if any fields are empty
        if(idNum.strip().equals("") || name.strip().equals("") ||
            name.strip().equals("")){
            error = true;
            JOptionPane.showMessageDialog(null,"Please fill in all fields.","Error",0);

            //check if name is too long
        }else if(name.length() > 50){
            error = true;
            JOptionPane.showMessageDialog(null,"Name is too long.","Error",0);
            txtName.grabFocus();

        }else if(!isNumeric(quantity)){
            error = true;
            JOptionPane.showMessageDialog(null,"Quantity must be a number","Error",0);
            txtQuantity1.grabFocus();
        }

        //only run if there are no errors
        if(!error){
            //confirmation message
            //this will bring up a confirmation box asking yes or no
            //yes will return 0
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you would like to update the record for:\nItem ID number " + idNum, "Update Confirmation", dialogButton);
            if(dialogResult == 0) {
                //continue with edit if yes
                //create a string for all of the info in a line
                String editedRecord = (idNum + ", " + name + ", " +
                    quantity);

                //get all records in list and replace the edited one
                for(int i = 0; i < records.length; i++){
                    //check if the record starts with the stock items id the user entered
                    //get the component at i and check if it starts with the id number
                    if(lstStock.getModel().getElementAt(i).startsWith(idNum)){
                        records[i] = editedRecord;

                        //get record that is currently in the list if the id number is different
                    }else{
                        records[i] = lstStock.getModel().getElementAt(i);
                    }
                }

                //debug code to see contents of list
                for(int i = 0; i < records.length; i++){
                    System.out.println("DEBUG: " + records[i]);
                }

                //rewrite file with array containing edited record
                try {
                    //create instance of the file writer with the chosen file path
                    FileWriter fw = new FileWriter("storage\\stock.txt");

                    //buffered writer for new line
                    BufferedWriter bw = new BufferedWriter(fw);

                    //loop through array
                    for(int i = 0; i < records.length; i++){
                        //write record from array
                        bw.write(records[i]);
                        //take new line
                        bw.newLine();
                    }

                    //close file
                    fw.flush();
                    bw.flush();

                } catch (IOException ex) {
                    //show error window
                    JOptionPane.showMessageDialog(null,"There was an error writing to the file.\n" + ex,"Error",0);
                }

                //show success mesage
                JOptionPane.showMessageDialog(null,"Edit successfully made.","Success",1);

                //clear fields
                lstStock.clearSelection();

                txtName.setText("");
                txtQuantity1.setText("");
                txtIDNum.setText("");

                //reload customer info to list
                loadList();
                
                //edit the data for the current stock objects
                //insert data into a new instance of the stock class
                appData.currentStock.setIdNum(Integer.valueOf(idNum));
                appData.currentStock.setQuantity(Integer.valueOf(quantity));
                appData.currentStock.setName(name);

                //debug code
                System.out.println("DEBUG: " + appData.currentStock.getIdNum());
                System.out.println("DEBUG: " + appData.currentStock.getQuantity());
                System.out.println("DEBUG: " + appData.currentStock.getName());
            } else {
                //do nothing
            }
            
            

        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void lstStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstStockMouseClicked
        //Fill in fields with customer data when a record is clicked
        //split line on every comma e.g. [0] = 1, [1] = Hair Dye, [2] = 35
        String [] record = lstStock.getSelectedValue().toString().split(", ");

        //fill in fields
        txtIDNum.setText(record[0]);
        txtName.setText(record[1]);
        txtQuantity1.setText(record[2]);
    }//GEN-LAST:event_lstStockMouseClicked

    private void txtIDNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDNumActionPerformed

    private void txtQuantity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantity1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAndEditStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAndEditStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAndEditStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAndEditStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewAndEditStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JList<String> lstStock;
    private javax.swing.JFormattedTextField txtIDNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JFormattedTextField txtQuantity1;
    // End of variables declaration//GEN-END:variables
}
